#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x paned_repl`
puts `gem build paned_repl.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }

`./bin/paned_repl init`


